title: LerntageBlog Bibliotheks- und Archivinformatik
author: Alex
email: alexandra.muster@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  LerntageBlog im Kurs Bibliotheks- und Archivinformatik HS 2020

# social links

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-merlot

